apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-city-weahter-app
  namespace: argocd 
spec:
  destination: 
    namespace: gitops-kubernetes-weather-app
    server: https://kubernetes.default.svc 
  project: default 
  source:
    repoURL: https://github.com/okeyobia/gitops-k8s-deployments-book-weather-app.git
    # path: deployment
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      prune: true
      selfHeal: true